{% set name = "flametree" %}
{% set version = "0.1.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flametree-{{ version }}.tar.gz
  sha256: 3bb9bbd422fa43c1328dc6afb505b646a2fcf0d55421df327425d4173aaefbca

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.3
  run:
    - python >=3.3

test:
  imports:
    - flametree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Edinburgh-Genome-Foundry/Flametree
  summary: Python file and zip operations made easy
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - tjacobs2
