{% set name = "flametree" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flametree-{{ version }}.tar.gz
  sha256: 6ee675fb7305d2a8d601cd117fb377a5395741eb05d6485a191fa3b2d119dd06

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.3
  run:
    - python >=3.3

test:
  imports:
    - flametree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Edinburgh-Genome-Foundry/Flametree
  summary: Python file and zip operations made easy
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - tjacobs2
